export enum InterestedRole {
  BACKEND_DEVELOPER = 'BACKEND_DEVELOPER',
  FRONTEND_DEVELOPER = 'FRONTEND_DEVELOPER',
  FULLSTACK_DEVELOPER = 'FULLSTACK_DEVELOPER',
  QA_TESTER = 'QA_TESTER',
  DATA_ANALYST = 'DATA_ANALYST',
  UX_UI_DESIGNER = 'UX_UI_DESIGNER',
  SUPPORT_IT = 'SUPPORT_IT',
  CYBERSECURITY_TRAINEE = 'CYBERSECURITY_TRAINEE',
}
