@baseUrl = http://localhost:3001
@accessToken =

### Create my profile
POST {{baseUrl}}/profiles/me
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "fullName": "Juan Perez",
  "ageRange": "25-34",
  "location": "Buenos Aires",
  "currentStatus": "buscando empleo",
  "headline": "Frontend Developer Junior",
  "professionalBio": "Estoy aprendiendo React y backend con NestJS",
  "yearsExperience": 1
}

### Get my profile
GET {{baseUrl}}/profiles/me
Authorization: Bearer {{accessToken}}

### Update my profile
PATCH {{baseUrl}}/profiles/me
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "headline": "Full Stack Developer Junior",
  "yearsExperience": 2
}

### Update my work preferences
PATCH {{baseUrl}}/profiles/me/preferences
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "country": "Argentina",
  "preferredModality": "HIBRIDO"
}

### Recalculate my employability score
PATCH {{baseUrl}}/profiles/me/employability-score
Authorization: Bearer {{accessToken}}
